#----------------------------#
#      General Settings      #
#----------------------------#

[settings]
color = true # color terminal output
use-unicode = true # use fancy symbols in terminal output. If false defaults to ascii text

#----------------------------#
#         Directories        #
#----------------------------#

[dir."$HOME"]
allowed-dirs = [
    { name = "Downloads" },
    { name = "Pictures" },
    { name = "Desktop" },
    { name = "Videos" },
    { name = "Music" },
    { name = "Documents" },
    { pattern = "^\\." }, # allow any hidden directory
]
allowed-files = [
    { pattern = "^\\." }, # allow any hidden file
]

[dir."$HOME/Videos"]
recursive = true # sub-folders will have the same rules
# no 'allowed-dirs' means any directory is valid
allowed-files = [
    { ext = "mp4" },
    { ext = "mov" },
    { ext = "mkv" },
]

# [dir."$HOME/Music"]
# recursive = true
# allowed-files = [
#     ".*\\.(mp3|m4a|flac|opus)$"
# ]

# [dir."$HOME/Downloads"]
# allowed-dirs = [
#     "Videos",
#     "Music",
#     "Misc",
# ]
# no 'allow-files' means any file is valid

#----------------------------#
#       Auto Move Rules      #
#----------------------------#

[automove]
report-info = "count" # display how many files could be
                      # automatically moved at the end of a report
                      # options are: "no", "any", "count"

[[automove.rules]]
parent = "$HOME"
match = [
    { ext = "mp4" },
    { ext = "mov" },
    { ext = "mkv" },
]
to = "$HOME/Videos"
